#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
#
echo "start"
install_version="7.4.3"

# Download and install XWiki

install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

#
# If XWiki is already installed in the current gear, there
# is nothing to build :-)
#
#[ -d "${current_version_dir}" ] && exit 0

mkdir -p $install_dir

pushd ${install_dir} >/dev/null
curl -s http://download.forge.ow2.org/xwiki/xwiki-enterprise-web-7.4.3.war > xwiki.war
echo "download xwiki.war"

#mv xwiki.war ${OPENSHIFT_REPO_DIR}/deployments/xwiki.war
#echo "mv to deployment folder"

# Verify the sources
#
#tarball_md5=$(md5sum xwiki.war | cut -d ' ' -f 1)
#xwiki_md5=$(curl -s http://maven.xwiki.org/releases/org/xwiki/enterprise/xwiki-enterprise-web/${install_version}/xwiki-enterprise-web-${install_version}.war.md5)
#if [ "${tarball_md5}" != "${xwiki_md5}" ]; then
#  echo "ERROR: XWiki ${install_version} MD5 checksum mismatch."
#  exit 1;
#fi

# explode war
unzip xwiki.war -d xwiki

# remove original
rm -rf xwiki.war 

# add libs
curl -s http://central.maven.org/maven2/com/google/inject/guice/3.0/guice-3.0.jar > xwiki/WEB-INF/lib/guice-3.0.jar
curl -s http://central.maven.org/maven2/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar > xwiki/WEB-INF/lib/guice-servlet-3.0.jar
curl -s http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.37/mysql-connector-java-5.1.37.jar > xwiki/WEB-INF/lib/h2-1.4.178.jar

# remove existing hibernate config
rm -f xwiki/WEB-INF/hibernate.cfg.xml

# grab correct hibernate config
curl -s https://raw.githubusercontent.com/jarpywang/jarpytest/master/pub/hibernate.cfg.xml > xwiki/WEB-INF/hibernate.cfg.xml

# repack war
jar cfvM wiki.war -C xwiki META-INF/ -C xwiki redirect -C xwiki resources/ -C xwiki skins/ -C xwiki templates/ -C xwiki WEB-INF

# remove exploded files
rm -rf xwiki/

# move war to the right location
#mv wiki.war ${OPENSHIFT_DEPENDENCIES_DIR}jbosseap/deployments/myxwiki.war

mv wiki.war ${OPENSHIFT_REPO_DIR}/deployments/wiki.war

popd >/dev/null